[project]
name = "tseg"
version = "0.1.0"
description = "Tumorous area segmentation with YOLO-based models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.3",
    "loguru>=0.7.3",
    "numpy>=2.2.2",
    "tqdm>=4.67.1",
    "typer>=0.15.1",
    "ultralytics>=8.3.23",
    "wandb>=0.19.6",
]
